<?php
$tr_from = "AÁBCČDĎEÉFGHIÍJKLźMNŇOÓPQRŘSŠTŤUŮÚVWXYÝZŽ"."aábcčdďeéfghiíjklžmnňoópqrřsštťuůúvwxyýzž";
$tr_to  = "AÁBCČDĎEÉFGHIÍJKLźMNŇOÓPQRŘSTUŮÚVWXYÝZ"."aábcčdďeéfghiíjklžmnňoópqrřstuůúvwxyýz";
$GLOBALS["tr_male"] = "aábcčdďeéfghiíjklžmnňoópqrřsštťuůúvwxyýzž";
$GLOBALS["tr_velke"] = "AÁBCČDĎEÉFGHIÍJKLźMNŇOÓPQRŘSŠTŤUŮÚVWXYÝZŽ";
$tr_male = "aábcčdďeéfghiíjklžmnňoópqrřsštťuůúvwxyýzž";
$tr_velke = "AÁBCČDĎEÉFGHIÍJKLźMNŇOÓPQRŘSTUŮÚVWXYÝZ";

?>
