<?php

if ($GLOBALS['POCET_PRILOH_2']>0) {
  $GLOBALS['DRUH_PRILOH'] = $GLOBALS["POCET_PRILOH"] . '/' . $GLOBALS["POCET_PRILOH_2"];
}
if ($GLOBALS['PRILOHY_ZAPOCITAT_2']>0) {
  $GLOBALS['PRILOHY_ZAPOCITAT'] = $GLOBALS["PRILOHY_ZAPOCITAT_2"]*10 + $GLOBALS["PRILOHY_ZAPOCITAT"];
}

