<?php
  $FORM_CONFIG["schema"][] = array("elements"=>array(
            array( "type"=>"date_db", "name"=>"DATUM","insertdatebutton"=>true,"required"=>true),
            ),
            "label"=>"Datum převzetí:");							
            

 $FORM_CONFIG["schema"][] = array("elements"=>array(
            array( "type"=>"textarea", "name"=>"CISLA","rows"=>30,"cols"=>30),
            ),   
            "label"=>"Sejmutá čísla:");		


?>
