<?php

$GLOBALS['CONFIG']['SCHVALOVANI'] = array(
    array('VALUE' => '0', 'ZADOST' => '', 'ODPOVED' => 'Před rozhodnutím'),
    array('VALUE' => '1', 'ZADOST' => 'Souhlas', 'ODPOVED' => 'Souhlasím'),
    array('VALUE' => '2', 'ZADOST' => '', 'ODPOVED' => '<font color="red">Nesouhlasím</font>'),
    array('VALUE' => '11', 'ZADOST' => 'Aprobaci (podpis)', 'ODPOVED' => 'Aprobuji (podepisuji)'),
    array('VALUE' => '12', 'ZADOST' => '', 'ODPOVED' => '<font color="red">Neschvaluji</font>'),
//    array('VALUE' => '2','LABEL' => 'Stítek test 2 (66x40)','X' => '10','Y' => '10','SLOUPCU' => '3','RADKU' => '7'),
);
//  'SCHVALOVANI_TAKE_JA' => false, //prida volbu Jsem také schvalující:


