<?php
$GLOBALS['RESOURCE_STRING']['lokace_uroven'] = array(
  1 => array(1 => 'Budova',   4 => 'Budovu',   8 => 'Budovy'), // 1 - 1. pad j. cisla, 4 - 4. pad j. cisla, 8 - 1. pad mn. cisla
  2 => array(1 => 'Místnost', 4 => 'Místnost', 8 => 'Místnosti'),
  3 => array(1 => 'Regál',    4 => 'Regál',    8 => 'Regály'),
  4 => array(1 => 'Paprsek',  4 => 'Paprsek',  8 => 'Paprsky'),
  5 => array(1 => 'Police',   4 => 'Polici',   8 => 'Police'),
);

$GLOBALS['RESOURCE_STRING']['lokace_novy'] = array(
  1 => 'novou',
  2 => 'novou',
  3 => 'nový',
  4 => 'nový',
  5 => 'novou',
);