
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-2">
  <TITLE>Tisk protokolu</TITLE>
  <LINK href="../print_style.css" rel="stylesheet" type="text/css">
  <style media="print"></style>
</HEAD>
<BODY>

<STYLE type="text/css">
BODY
{
font-family: 	arial;
}
TABLE
{
font-size:	x-small;
}
</STYLE>

<!--<BODY class="mojebody">-->
<!--odladěno pro MSIE 5.0-->
<table width="640" align="center"><!--sirka tabulky odladena pro HPLJ4P-->
<tr>
<td>

<table width="100%" border=0 align=center>

<?php
include(FileUp2('.admin/config.inc'));
echo "
<tr><td class=\"stred\" align=center><center><img src=\"images/logo.gif\" alt=\"".$CONFIG["URAD"].$CONFIG["MESTO"]."\" border=\"0\" width=\"520\" align=center ></center></td></tr>
";
?>

</table>
<BR>
<!--hr class="cerny" size="1"-->
</td>
<td width="50%"></td>
</tr></table>

