<?php
$TABLE_CONFIG["schema"][] =  array( "field"=>"ShowObjekt(OBJEKT)", "label"=>"Objekt","width"=>"30%");
$TABLE_CONFIG["schema"][] =  array( "field"=>"SOURX", "label"=>"pozice X","width"=>"10%");
$TABLE_CONFIG["schema"][] =  array( "field"=>"SOURY", "label"=>"pozice Y","width"=>"10%");
$TABLE_CONFIG["schema"][] =  array( "field"=>"VELIKOST", "label"=>"Délka","width"=>"10%");
$TABLE_CONFIG["schema"][] =  array( "field"=>"VELIKOST_FONTU", "label"=>"Písmo","width"=>"10%");
$TABLE_CONFIG["schema"][] =  array( "field"=>"RADKOVANI", "label"=>"Řádkování","width"=>"10%");
$TABLE_CONFIG["schema"][] =  array( "field"=>"TEXT", "label"=>"text","width"=>"20%");

?>
