<?php
//$TABLE_CONFIG["schema"][] = array("field"=>"JID", "label"=>"<font color='black'>JID</font>",  "width"=>"1%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"REJSTRIKOVECISLO", "label"=>"<font color='black'>Rejs.číslo</font>",  "width"=>"1%","add"=>"align=left",'is_html'=>true);
$TABLE_CONFIG["schema"][] = array("field"=>"JMENO", "label"=>"<font color='black'>Název</font>",  "width"=>"30%","add"=>"align=left",'is_html'=>true);
$TABLE_CONFIG["schema"][] = array("field"=>"KATASTR", "label"=>"<font color='black'>Katastr</font>",  "width"=>"10%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"ADRESA", "label"=>"<font color='black'>Adresa</font>",  "width"=>"10%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"KATEGORIEPRVKU", "label"=>"<font color='black'>Kategorie</font>",  "width"=>"10%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"OCHRANA", "label"=>"<font color='black'>Typ ochrany</font>",  "width"=>"10%","add"=>"align=left",'is_html'=>true);
$TABLE_CONFIG["schema"][] = array("field"=>"TYP", "label"=>"<font color='black'>Typ</font>",  "width"=>"10%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"Url(URL)", "label"=>"",  "width"=>"1%","class"=>"image");

  
