<?php
$GLOBALS['CONFIG_POSTA_CESKAPOSTA']=array(
  'DO_PROTOKOLU_JEN_CK' => true, //jen obalky prevzate na podatelnu se budou nabizet
  'PODATELNA_ODBOR_BEZ_CK' => true, //pokud je 'DO_PROTOKOLU_JEN_CK', pak podatelna odbor nemusi predavat pres CK
  'V_PROTOKOLU_SPIS_ZKRATKA' => true, //po poznamky v protokolu umisit zkratku uzlu

  'USE_R_KODY' => true, //budou se generovat Rkove kody pro Ceskou postu

  'TRIDIT_DLE_DATUM_PREDANI' => true,
);