<?php

$PROPERTIES["MENU2L"]["new"] = array(
 '0' => "Vlož odchozí",
 '1' => "javascript:NewWindow('".$url."edit.php?insert&odeslana=t&cacheid=');",
 'icon' => InsertImage('images/back', '', '', array('img_sizes'=>false)),
);

//if (!HasRole('spravce'))
//   $PROPERTIES["MENU2L"]["cis"] = array(
//    '0' => "Vlož vnitřní",
//    '1' => "javascript:NewWindow('".$url."edit.php?insert&odeslana=t&vnitrni=t&cacheid=');",
//    'icon' => InsertImage('images/back', '', '', array('img_sizes'=>false)),
//   );


//   $PROPERTIES["MENU2P"]["agenda"] = array(
//    '0' => "Vlož vnitřní",
//    '1' => "javascript:NewWindow('".$url."edit.php?insert&odeslana=t&vnitrni=t&cacheid=');",
//    'icon' => InsertImage('images/add', '', '', array('img_sizes'=>false)),
//    'target' => '_self'
//   );
