<?php
  $TABLE_CONFIG["schema"][]= array( field=>"PORADOVE", "label"=>"Pořad.", width=>"10%", is_html => true);
//  $TABLE_CONFIG["schema"][]= array( field=>"ROK_PREDANI", "label"=>"Předáno", width=>"10%");
  $TABLE_CONFIG["schema"][]= array( field=>"ODBOR_TEXT", "label"=>"Spis.uzel", width=>"10%", is_html => true);
  $TABLE_CONFIG["schema"][]= array( field=>"VLOZENA_CJ", "label"=>"ČJ", width=>"10%");
  $TABLE_CONFIG["schema"][]= array( field=>"VEC", "label"=>"Věc", width=>"10%");
  $TABLE_CONFIG["schema"][]= array( field=>"ROK_PREDANI", "label"=>"Uzavřeno", width=>"10%");
  $TABLE_CONFIG["schema"][]= array( field=>"SKARTACE_TEXT", "label"=>"Spis.znak", width=>"10%", is_html => true);
  $TABLE_CONFIG["schema"][]= array( field=>"SKAR_ZNAK", "label"=>"Písm", width=>"10%");
  $TABLE_CONFIG["schema"][]= array( field=>"LHUTA", "label"=>"lhůta", width=>"10%");
  $TABLE_CONFIG["schema"][]= array( field=>"LAST_USER_TEXT", "label"=>"Předal", width=>"10%", is_html => true);
  $TABLE_CONFIG["schema"][]= array( field=>"PREVZAL_TEXT", "label"=>"Převzal", width=>"10%", is_html => true);
  $TABLE_CONFIG["schema"][]= array( field=>"LAST_DATE", "label"=>"Dne", width=>"10%");
  $TABLE_CONFIG["schema"][]= array( field=>"ROK_SKARTACE", "label"=>"Vyřazeno", width=>"10%");
  $TABLE_CONFIG["schema"][]= array( field=>"POZNAMKA", "label"=>"Pozn.", width=>"10%");

