<?php
// $TABLE_CONFIG["schema"][] = array( field=>"ID", label=>"ID", add=>"align=center", "order_by"=>"id","width"=>"1%");
// $TABLE_CONFIG["schema"][] = array( field=>"KATEGORIE", label=>"Kategorie", add=>"left", "order_by"=>"kategorie","width"=>"10%");
// $TABLE_CONFIG["schema"][] = array( field=>"PARAMETR", label=>"Parametr", add=>"left", "order_by"=>"parametr","width"=>"15%");
// $TABLE_CONFIG["schema"][] = array( field=>"HODNOTA", label=>"Hodnota", add=>"left", "order_by"=>"hodnota","width"=>"25%");
// $TABLE_CONFIG["schema"][] = array( field=>"'<font size=1>'...POPIS...'</font>'", label=>"Popis","width"=>"50%");


$TABLE_CONFIG["schema"][] =  array( "field"=>"UkazOdbor(ODBOR)", "label"=>"Spisový uzel", "width"=>"25%");
$TABLE_CONFIG["schema"][] = array( field=>"PARAMETR", label=>"Parametr", add=>"left", "order_by"=>"parametr","width"=>"40%");
$TABLE_CONFIG["schema"][] = array( field=>"HODNOTA", label=>"Hodnota", add=>"left", "order_by"=>"hodnota","width"=>"60%");

