<?php
$TABLE_CONFIG["schema"][] = array("field"=>"ID", "label"=>"ID DS",  "width"=>"1%","add"=>"align=center");
$TABLE_CONFIG["schema"][] = array("field"=>"Stav", "label"=>"Stav",  "width"=>"10%","add"=>"align=center");
$TABLE_CONFIG["schema"][] = array("field"=>"MAJITEL", "label"=>"Majitel",  "width"=>"35%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"ICO", "label"=>"IČ/dat.nar.",  "width"=>"10%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"ADRESA", "label"=>"Adresa",  "width"=>"45%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"NARODNOST", "label"=>"Národnost",  "width"=>"10%","add"=>"align=left");

  
