<?php

$TABLE_CONFIG["schema"][] = array("field"=>"ID", "label"=>"id",  "width"=>"1%","add"=>"align=center");
$TABLE_CONFIG["schema"][] = array("field"=>"NASE_CJ", "label"=>"čj.",  "width"=>"7%","add"=>"align=left NOWRAP");
$TABLE_CONFIG["schema"][] = array("field"=>"NAS_SPIS", "label"=>"spis",  "width"=>"8%","add"=>"align=left NOWRAP");
$TABLE_CONFIG["schema"][] = array("field"=>"DATUM", "label"=>"Datum",  "width"=>"10%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"FROM", "label"=>"příjemce",  "width"=>"20%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"VEC", "label"=>"Věc",  "width"=>"20%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"VYPRAVENI", "label"=>"vypravení",  "width"=>"20%","add"=>"align=left");
$TABLE_CONFIG["schema"][] = array("field"=>"DORUCENI", "label"=>"doručení",  "width"=>"20%","add"=>"align=left");
