<?php
$TABLE_CONFIG = array(//  "callback"=> "ChangeClassBarva",
  "schema" => array( 
    array( field=>"NAZEV", label=>"Aplikace","width"=>"100%"),
//    array( field=>"ShowUrl(ID,'PRICHOZI')", label=>"Příchozí&nbsp;DZ", "width"=>"10%"),
//    array( field=>"ShowUrl(ID,'ODCHOZI')", label=>"Odchozí&nbsp;DZ", "width"=>"10%"),
//    array( field=>"ShowUrl(ID,'DORUCENKY')", label=>"Doručenky", "width"=>"10%"),
    
  )
 );
