<?php
$GUIDE_PROP["posta_prijemci"] = array("dir"=>"posta_prijemci", "def_form"=>"Guide");
$GUIDE_PROP["posta_adresati"] = array("dir"=>"posta_adresati", "def_form"=>"Guide");
$GUIDE_PROP["posta_spisy"] = array("dir"=>"posta_spisy", "def_form"=>"Guide");
$GUIDE_PROP["posta_adresy"] = array("dir"=>"posta_adresy", "def_form"=>"Guide");
$GUIDE_PROP["posta_firmy"] = array("dir"=>"posta_firmy", "def_form"=>"Guide");
$GUIDE_PROP["posta_vytvorspis"] = array("dir"=>"posta_vytvorspis", "def_form"=>"Guide");
$GUIDE_PROP["obyvatele"] = array("dir"=>"obyvatele", "def_form"=>"Guide");
$GUIDE_PROP["posta_cjednaci"] = array("dir"=>"posta_cjednaci", "def_form"=>"Guide");
$GUIDE_PROP["posta_dalsispisy"] = array("dir"=>"posta_dalsispisy", "def_form"=>"Guide");
$GUIDE_PROP["posta_dalsicjspisy"] = array("dir"=>"posta_dalsicjspisy", "def_form"=>"Guide"); // pro pridani do spisu - lze pridat CJ nebo SPIS (spis do spisu)
$GUIDE_PROP["posta_dalsicj"] = array("dir"=>"posta_dalsicj", "def_form"=>"Guide");
$GUIDE_PROP["posta_krizspisy"] = array("dir"=>"posta_krizspisy", "def_form"=>"Guide");
$GUIDE_PROP["posta_psc"] = array("dir"=>"posta_psc", "def_form"=>"Guide");
$GUIDE_PROP["posta_DS"] = array("dir"=>"posta_DS", "def_form"=>"Guide");
$GUIDE_PROP["posta_iszr"] = array("dir"=>"posta_iszr", "def_form"=>"Guide");
$GUIDE_PROP["posta_typ"] = array("dir"=>"posta_typ", "def_form"=>"Guide");
