<?php

//$PROPERTIES['MENU1P']['ag_all'] = array('Název', 'skript.php');

//$PROPERTIES['MENU2L']['filterall'] = false;
//$PROPERTIES['MENU2L']['new'] = false;
//$PROPERTIES['MENU2L']['new'] = array('Nový záznam', 'javascript:NewWindow(\'edit.php?insert&cacheid=\');');

$PROPERTIES['MENU1P']['ds'] = array('Zpět do DS', '/'.GetAgendaPath('POSTA_DS'));

include(FileUp2('posta/.admin/prop_menu_theme.inc'));